USE [COSMICs]
GO
/****** Object:  UserDefinedFunction [dbo].[func_getData_COT_SHIPPING_ISSUE_FG]    Script Date: 12/12/2017 2:08:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		SSD.N
-- Create date: 12-nov-2017
-- Description:	สำหรับเรียกข้อมูล COT_SHIPPING_ISSUE_FG
-- =============================================
ALTER FUNCTION [dbo].[func_getData_COT_SHIPPING_ISSUE_FG]
(	
	@DYEAR smallInt,
	@DMONTH tinyInt
)
RETURNS 
--Generated by Smart Suite Development : 11/12/2017 4:10:11 PM
 @SSDISSUE    TABLE (YPARTNO VARCHAR(50),
ISSUED_QTY DECIMAL(38,7),
PRODUCTION_IMPORT_TAX_ISSUE_QTY DECIMAL(38,7),
ISSUED_AMOUNT DECIMAL(10,3)
)
AS
BEGIN
	-- Fill the table variable with the rows for your result set
	 --- issue Qty ---102------- 

--UPDATE MANAUL
--SSD.N 17-nov-2017  Mapping PartNo from AS400 into COSTING & SHIPPING


--Generated by Smart Suite Development : 11/17/2017 2:52:52 PM
DECLARE @COT_SHIPPING_ISSUE_FG  AS TABLE (CUSTID VARCHAR(8),
PARTNO VARCHAR(51),
QTY DECIMAL(38,7),
TYPE VARCHAR(20),
PRICE DECIMAL(10,3),
ISSUED_AMOUNT DECIMAL(10,3) 
)
INSERT INTO @COT_SHIPPING_ISSUE_FG (CUSTID,PARTNO,QTY,TYPE)
select CUSTID,
		CASE  
			WHEN (CHARINDEX(' ',naypat) > 0 AND CUSTID = '32T2C')  
				THEN SUBSTRING(naypat,0, CHARINDEX(' ',naypat)) + 'C'  
			WHEN  CHARINDEX(' ',naypat) > 0 
				THEN SUBSTRING(naypat,0, CHARINDEX(' ',naypat))
			ELSE 
				naypat  
			END AS PARTNO ,sum(qty_m) as ProAmount_qty,TYPE
	from [dbo].[COT_SHIPPING_ISSUE_FG]
	where  INPUTTYPE = 'Transfer' and year(DDATE) = @DYEAR and month(ddate) = @DMONTH -- and type like 'Dom%'
	group by CUSTID,naypat,TYPE

--INCLUDE PRICE
--ตรวจสอบ ราคา
UPDATE C 
SET
C.PRICE = 
	CASE 
		WHEN [TYPE] LIKE 'Dom%' AND CUSTID LIKE '32T2%'  THEN  P.WIP_PRICE_DOM_TAPC
		WHEN [TYPE] LIKE 'Dom%' AND CUSTID NOT IN('32T2D','32T3') THEN  P.WIP_PRICE_DOM_OTHER
		WHEN [TYPE] LIKE 'Dom%' AND CUSTID = '32T3' THEN  P.WIP_PRICE_EXP
		ELSE  P.WIP_PRICE_EXP
		END
	
FROM
@COT_SHIPPING_ISSUE_FG C
INNER JOIN(
	select PARTNO,MATCOST_DIRECT,MATCOST_IMPTAX,MATCOST_INDIRECT,WIP_PRICE_EXP,WIP_PRICE_DOM_OTHER,WIP_PRICE_DOM_TAPC,WIP_PRICE_AMORTI
	 from COT_MST_COSTING_PRICELIST
	where DYEAR=@DYEAR and DMONTH=@DMONTH AND PARTTYPE='F'
) P
ON C.PARTNO = P.PARTNO


--คำนวน  AMOUNT
UPDATE @COT_SHIPPING_ISSUE_FG
SET ISSUED_AMOUNT = QTY * ISNULL(PRICE,0)

---ISSUE
INSERT INTO @SSDISSUE
select PARTNO,sum(QTY) as Iss_qty,NULL,SUM(ISSUED_AMOUNT)
from @COT_SHIPPING_ISSUE_FG
--where  INPUTTYPE = 'Transfer' and year(DDATE) = @DYEAR and month(ddate) = @DMONTH 
group by PARTNO
order by PARTNO 


--Generated by Smart Suite Development : 11/12/2017 4:10:19 PM
DECLARE @SSDPRODUCTION  AS TABLE (naypat VARCHAR(50),
ProAmount_qty DECIMAL(38,7))
--INSERT INTO @SSDPRODUCTION
----- Pro Amount Qty ---79-------
--select CASE CHARINDEX(' ',naypat) WHEN 0 THEN naypat ELSE SUBSTRING(naypat,0, CHARINDEX(' ',@VAL)) + 'C'  END ,sum(qty_m) as ProAmount_qty
--from [dbo].[COT_SHIPPING_ISSUE_FG]
--where  INPUTTYPE = 'Transfer' and year(DDATE) = @DYEAR and month(ddate) = @DMONTH  and type like 'Dom%'
--group by naypat
--order by NAYPAT
INSERT INTO @SSDPRODUCTION
 SELECT PARTNO,SUM(QTY)
 FROM @COT_SHIPPING_ISSUE_FG
 WHERE TYPE  LIKE 'DOM%'
GROUP BY PARTNO
 

 

MERGE @SSDISSUE AS T
USING @SSDPRODUCTION AS S
ON (T.YPARTNO = S.naypat )
WHEN NOT MATCHED BY TARGET
    THEN INSERT(YPARTNO, PRODUCTION_IMPORT_TAX_ISSUE_QTY) VALUES(S.naypat, S.ProAmount_qty)
WHEN MATCHED 
    THEN UPDATE SET T.PRODUCTION_IMPORT_TAX_ISSUE_QTY = S.ProAmount_qty;





	RETURN --(SELECT * FROM @SSDISSUE)
END


